# Server settings
server:
    port: 8888

# SPRING PROFILES
spring:
    application:
        name: security-demo
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot-security-demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true

ittochat:
  security:
    browser:
      loginPage: /demo-signIn.html